<a href="https://colab.research.google.com/github/Praagnya/pytorch/blob/main/Pytorch_Fundamentals_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.youtube.com/watch?v=V_xro1bcAuA&t=2598s

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [5,7,8]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [5, 7, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [5, 7, 8]])

### Random Tensors


In [16]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4572, 0.4975, 0.5824, 0.7590],
        [0.1588, 0.4155, 0.1325, 0.1156],
        [0.8459, 0.5437, 0.4981, 0.6028]])

In [17]:
random_tensor.size

<function Tensor.size>

In [18]:
torch.rand(4)

tensor([0.4456, 0.3145, 0.6067, 0.9112])

In [19]:
torch.rand(2,3)

tensor([[0.9463, 0.0216, 0.6783],
        [0.2468, 0.6162, 0.4164]])

In [20]:
# create a random tensor with similar shape tp an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

## creating a range of tensors and tensors-like

In [24]:
torch.arange(0, 1000, 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [25]:
### Creating tensors like --> creates tensors of the same size and shape of the input = -----
one_to_ten = torch.arange(1,10,1)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [26]:
float_32_tensor = torch.tensor([4, 6, 7],
                               dtype = None, # what datatype is the tensor (e.g. float32 or float64)
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.int64

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4., 6., 7.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([16., 36., 49.], dtype=torch.float16)

In [29]:
float_16_tensor.device

device(type='cpu')

In [30]:
some_tensor = torch.rand(3, 4).type(torch.float16)
some_tensor.dtype

torch.float16

In [31]:
# Manipulation tensors

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
# try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [37]:
tensor1 = torch.randint(0,10, size=(3,2))
tensor2 = torch.randint(0,10, size=(2,3))
print(tensor1)
print(tensor2)
tensor1.matmul(tensor2)

tensor([[8, 1],
        [7, 4],
        [1, 6]])
tensor([[2, 1, 5],
        [1, 2, 5]])


tensor([[17, 10, 45],
        [18, 15, 55],
        [ 8, 13, 35]])

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.85 ms, sys: 119 µs, total: 1.97 ms
Wall time: 4.01 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 539 µs, sys: 76 µs, total: 615 µs
Wall time: 7.93 ms


tensor(14)

### Shape errors
1. Inner dimensions should match
* `(3, 2) @ (3, 2)` won't work since the inner dimensions are not same
* `(3, 2) @ (2, 3)` will work since the inner dimensions are same
2. Outer dimensions shape will be the resulting vector/matrix
* `(3, 2) @ (2, 3)` the resulting vector will be (3, 3)
* `(1, 3) @ (3, 1)` the resulting vector wil be (1, 1)

In [40]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,11]])

# Transpose

In [41]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 11]])

In [42]:
tensor_A.mm(tensor_B.T)

tensor([[ 27,  30,  31],
        [ 61,  68,  71],
        [ 95, 106, 111]])

In [43]:
print(f"Tensor A shape: {tensor_A.shape}")
print(f"Tensor B shape: {tensor_B.T.shape}")

Tensor A shape: torch.Size([3, 2])
Tensor B shape: torch.Size([2, 3])


In [44]:
## Findind the mean, maedian, sum, max (tensor aggregation)

In [45]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
x.type(torch.float32).mean()

tensor(45.)

In [50]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [51]:
torch.argmax(x)

tensor(9)

In [52]:
tensor[0]

tensor(1)

In [53]:
torch.argmin(x)

tensor(0)

In [54]:
x[9]

tensor(90)

In [55]:
x[0]

tensor(0)

### Reshaping, Stacking, Squeezing and Unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimesnions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with the dimensions permuted(swapped) in a certain way  

In [56]:
import torch

x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [57]:
# Reshape
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [58]:
# Change the View
z = x.view( 1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

* Changing `z` will change `x` (because a view of a tensor shares the same memory as the original input)

In [59]:
# Stack
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [60]:
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.ndim)
print('--------------------')
x_reshaped = tensor.squeeze()
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.ndim)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([5, 2])
2
--------------------
tensor([1, 2, 3])
torch.Size([3])
1


In [61]:
print(x_reshaped)
print(x_reshaped.shape)


print('---')
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([1, 2, 3])
torch.Size([3])
---
tensor([[1, 2, 3]])
torch.Size([1, 3])


In [62]:
# torch.permute - rearranges the dimenssions of a target tensor in a specified order

In [63]:
x = torch.rand(size=(224, 224, 3))
print(x.shape)

x_permuted = x.permute(2, 0, 1) # Returns a different view from the original tensor but the memory of both the tensors will be same.
x_permuted.shape

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

### Indexing

In [64]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
x[0] #

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0][2][2]

tensor(9)

In [67]:
x[0][2][2]

tensor(9)

In [68]:
x[0,2,2]

tensor(9)

In [69]:
x[0,:,2]

tensor([3, 6, 9])